fold_folder: configs/dataset/peso/two/
id0:
  labeled: true
  n_regions: 11
id1:
  labeled: true
  n_regions: 7
id10:
  labeled: true
  n_regions: 5
id11:
  labeled: true
  n_regions: 1
id12:
  labeled: false
  n_regions: -1
id13:
  labeled: false
  n_regions: -1
id14:
  labeled: false
  n_regions: -1
id15:
  labeled: false
  n_regions: -1
id16:
  labeled: true
  n_regions: 8
id17:
  labeled: true
  n_regions: 5
id18:
  labeled: true
  n_regions: 4
id19:
  labeled: false
  n_regions: -1
id2:
  labeled: true
  n_regions: 4
id3:
  labeled: true
  n_regions: 8
id4:
  labeled: false
  n_regions: -1
id5:
  labeled: false
  n_regions: -1
id6:
  labeled: false
  n_regions: -1
id7:
  labeled: false
  n_regions: -1
id8:
  labeled: true
  n_regions: 7
id9:
  labeled: false
  n_regions: -1
length: 2000
n_files: 1
server:
  labeled: false
  length: 2000
  n_files: 4
  n_regions: -1
