fold_folder: configs/dataset/peso/two/
id0:
  labeled: false
  n_regions: -1
id1:
  labeled: true
  n_regions: 10
id10:
  labeled: false
  n_regions: -1
id11:
  labeled: true
  n_regions: 1
id12:
  labeled: true
  n_regions: 10
id13:
  labeled: true
  n_regions: 2
id14:
  labeled: true
  n_regions: 8
id15:
  labeled: true
  n_regions: 11
id16:
  labeled: true
  n_regions: 6
id17:
  labeled: false
  n_regions: -1
id18:
  labeled: true
  n_regions: 4
id19:
  labeled: false
  n_regions: -1
id2:
  labeled: false
  n_regions: -1
id3:
  labeled: false
  n_regions: -1
id4:
  labeled: false
  n_regions: -1
id5:
  labeled: false
  n_regions: -1
id6:
  labeled: true
  n_regions: 2
id7:
  labeled: false
  n_regions: -1
id8:
  labeled: false
  n_regions: -1
id9:
  labeled: true
  n_regions: 6
length: 2000
n_files: 1
server:
  labeled: false
  length: 2000
  n_files: 4
  n_regions: -1
