clients:
  n_clients: 20
  base: configs/federations/clients/base_wo_bottle_gan.yaml
server:  
  base: configs/federations/server/base_wo_bottle_gan.yaml
style_noise: 0.0
inter_emb: False
server_path: None
ssl_type: None
gauss_weights: False