clients:
  n_clients: 20
  base: configs/federations/clients/base.yaml
server:  
  base: configs/federations/server/base.yaml
style_noise: 0.0
inter_emb: False
server_path: None
ssl_type: None
gauss_weights: False