fold_folder: configs/dataset/peso/three/
id0:
  labeled: false
  n_regions: -1
id1:
  labeled: false
  n_regions: -1
id10:
  labeled: true
  n_regions: 2
id11:
  labeled: true
  n_regions: 2
id12:
  labeled: false
  n_regions: -1
id13:
  labeled: false
  n_regions: -1
id14:
  labeled: false
  n_regions: -1
id15:
  labeled: true
  n_regions: 10
id16:
  labeled: true
  n_regions: 7
id17:
  labeled: true
  n_regions: 8
id18:
  labeled: true
  n_regions: 10
id19:
  labeled: false
  n_regions: -1
id2:
  labeled: false
  n_regions: -1
id3:
  labeled: true
  n_regions: 4
id4:
  labeled: true
  n_regions: 1
id5:
  labeled: true
  n_regions: 11
id6:
  labeled: false
  n_regions: -1
id7:
  labeled: true
  n_regions: 5
id8:
  labeled: false
  n_regions: -1
id9:
  labeled: false
  n_regions: -1
length: 2000
n_files: 1
server:
  labeled: false
  length: 2000
  n_files: 4
  n_regions: -1
