fold_folder: configs/dataset/peso/three/
id0:
  labeled: false
  n_regions: -1
id1:
  labeled: false
  n_regions: -1
id10:
  labeled: false
  n_regions: -1
id11:
  labeled: true
  n_regions: 8
id12:
  labeled: false
  n_regions: -1
id13:
  labeled: true
  n_regions: 3
id14:
  labeled: false
  n_regions: -1
id15:
  labeled: false
  n_regions: -1
id16:
  labeled: true
  n_regions: 9
id17:
  labeled: true
  n_regions: 10
id18:
  labeled: false
  n_regions: -1
id19:
  labeled: false
  n_regions: -1
id2:
  labeled: false
  n_regions: -1
id3:
  labeled: true
  n_regions: 7
id4:
  labeled: false
  n_regions: -1
id5:
  labeled: true
  n_regions: 5
id6:
  labeled: true
  n_regions: 2
id7:
  labeled: true
  n_regions: 2
id8:
  labeled: true
  n_regions: 10
id9:
  labeled: true
  n_regions: 4
length: 2000
n_files: 1
server:
  labeled: false
  length: 2000
  n_files: 4
  n_regions: -1
