fold_folder: configs/dataset/peso/one/
id0:
  labeled: false
  n_regions: -1
id1:
  labeled: true
  n_regions: 7
id10:
  labeled: true
  n_regions: 3
id11:
  labeled: true
  n_regions: 3
id12:
  labeled: true
  n_regions: 6
id13:
  labeled: false
  n_regions: -1
id14:
  labeled: false
  n_regions: -1
id15:
  labeled: false
  n_regions: -1
id16:
  labeled: false
  n_regions: -1
id17:
  labeled: false
  n_regions: -1
id18:
  labeled: true
  n_regions: 9
id19:
  labeled: true
  n_regions: 7
id2:
  labeled: false
  n_regions: -1
id3:
  labeled: false
  n_regions: -1
id4:
  labeled: false
  n_regions: -1
id5:
  labeled: true
  n_regions: 5
id6:
  labeled: false
  n_regions: -1
id7:
  labeled: true
  n_regions: 5
id8:
  labeled: true
  n_regions: 6
id9:
  labeled: true
  n_regions: 9
length: 2000
n_files: 1
server:
  labeled: false
  length: 2000
  n_files: 4
  n_regions: -1
