embedding: configs/embeddings/unet.yaml 
predictor: configs/predictors/scaled.yaml
task: configs/tasks/train/single/base.yaml
unlabeled_task: configs/tasks/train/single/base.yaml
test_task: configs/tasks/test/single/base.yaml
stain_restainer_path: store/gans/all_stain_inc_meta.pt
unlabeled_stain_restainer_path: store/gans/all_stain_inc_meta.pt
data: 
augmentations: configs/augmentations/off.yaml
unlabeled_augmentations: configs/augmentations/off.yaml