weak_augmentations:
  transforms_per_image: 1
  random_apply: 0.5
  augmentations:
    rotation:
      p: 1.0
      degrees: 360
    flip:
      p: 1.0
    elastic:
      p: 1.0
      sigma: 3
      points: 18
strong_augmentations:
  transforms_per_image: 3
  random_apply: 1.0
  augmentations:
    equalize:
      p: 1.0
    solarize:
      p: 0.0
    posterize:
      p: 1.0
    color:
      p: 1.0
      range: 0.5
    sharpness:
      p: 1.0
      range: 0.5
    cutmix:
      p: 1.0
      max_h_ratio: 0.65
      max_w_ratio: 0.65
      min_h_ratio: 0.35
      min_w_ratio: 0.35
    grayscale:
      p: 1.0
    colorjitter:
      p: 1.0
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
    gauss:
      p: 1.0
      radius: 1.5
    jpeg:
      p: 1.0
      ratio: 10
    brightness_contrast:
      p: 1.0
      range: 0.6
    dark_spots:
      p: 1.0
      n_spots: 5
      alpha: 1.0
    threads:
      p: 1.0
      n_threads: 5
      alpha: 1.0
    squamous:
      p: 1.0
      n_threads: 5
      alpha: 1.0
    fat:
      p: 1.0
      n_threads: 5
      alpha: 1.0