weak_augmentations:
  transforms_per_image: 0 
  random_apply: 0.0
  augmentations:
    empty: None
strong_augmentations:
  transforms_per_image: 0
  random_apply: 0.0
  augmentations: 
    empty: None